### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by john-deng** [hidevopsio/hiboot#64]
**Describe the bug**

use wrk to test concurrent requests
```bash
wrk -t10 -c10 -d10s http://localhost:8080/user/id/1  

......

[INFO] 2019/02/09 23:24 200 2.204µs ::1 GET /user/id/1
fatal error: concurrent map writes

goroutine 189 [running]:
runtime.throw(0x17e3901, 0x15)
    /Users/johnd/.gvm/gos/go1.11/src/runtime/panic.go:608 +0x72 fp=0xc00052d278 sp=0xc00052d248 pc=0x102bfe2
runtime.mapassign_faststr(0x174fb60, 0xc0004f4090, 0x17dc672, 0xc, 0x0)
    /Users/johnd/.gvm/gos/go1.11/src/runtime/map_faststr.go:275 +0x3bf fp=0xc00052d2e0 sp=0xc00052d278 pc=0x1013dcf
net/textproto.MIMEHeader.Set(0xc0004f4090, 0x17dc672, 0xc, 0xc0003f0080, 0x1f)
    /Users/johnd/.gvm/gos/go1.11/src/net/textproto/header.go:22 +0xaf fp=0xc00052d330 sp=0xc00052d2e0 pc=0x122927f
net/http.Header.Set(0xc0004f4090, 0x17dc672, 0xc, 0xc0003f0080, 0x1f)
    /Users/johnd/.gvm/gos/go1.11/src/net/http/header.go:32 +0x53 fp=0xc00052d368 sp=0xc00052d330 pc=0x128b233
github.com/kataras/iris/context.(*context).ContentType(0xc0003022d0, 0xc0003f0080, 0x1f)

```
**Expected behavior**
```bash
Running 1m test @ http://localhost:8080/user/id/1
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   266.48us  182.38us  14.76ms   95.18%
    Req/Sec     3.88k   152.35     4.48k    77.97%
  2319630 requests in 1.00m, 442.43MB read
Requests/sec:  38595.88
Transfer/sec:      7.36MB
```

**Steps to reproduce the bug**

1. Run Hiboot application
2. Run load test command  `wrk -t10 -c10 -d10s http://localhost:8080/user/id/1  `
3. Show error `fatal error: concurrent map writes`

**Version**
1.0.0

**Environment**
Linux

**Comment by john-deng** [comment]
This bug is fixed by PR #66
